[package]
name = "tidal"
version = "0.1.0"
authors = ["TwoBytesShort <44448677+TwoBytesShort@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
